[server]
headless = true
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0A0E13"
secondaryBackgroundColor = "#0C1017"
textColor = "#C9D1D9"
primaryColor = "#00E5FF"
font = "monospace"
